### ISSUE TITLE
Make sure we can scale to lots of runtimes

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2349]
We should make sure we can scale to lots of runtimes by creating a test case which registers lots of runtimes (can be simple runtimes) and does some benchmarks.

A lighter test with multiple runtimes should also be added as an E2E test to ensure that everything works correctly with multiple runtimes.

**Comment by kostko** [comment]
There is an overhead for runtimes (even ones that don't submit any commitments) as certain actions need to happen on each epoch transition (committee election, inserting epoch transition blocks).

**Comment by matevz** [comment]
In #2529 `RuntimeID` is now passed dynamically to the worker and is not compiled in the binary anymore. To test this, new e2e test `multiple-runtimes` which loads arbitrary number of runtimes using the same runtime binary was added.

Additionally, a number of race conditions and hangs have been fixed in #2650 and #2669. We were able to repeatedly run `multiple-runtimes` with 32 runtimes using a single worker on a machine with 16 GiB of memory. Enabling SGX required a little more than 2x the amount of memory.

More detailed benchmarks will be done in #2536. Closing.
