### ISSUE TITLE
Simplify sentry node setup

### ISSUE THREAD

**Issue by tjanez** [oasislabs/oasis-core#2362]
After [initial Sentry node support is implemented](https://github.com/oasislabs/oasis-core/pull/2300), simplify the sentry node setup:
- Instead of manually and statically specifying sentry nodes as validator's persistent peers, support automatically configuring them upon querying sentry nodes for their consensus addresses and automatically restarting the Tenderming service (if necessary).
- Instead of manually disabling Tendermint's Peer exchange reactor when using sentry nodes, do that automatically (if sentry nodes are configured).

**Comment by ptrus** [comment]
> Instead of manually and statically specifying sentry nodes as validator's persistent peers, support automatically configuring them upon querying sentry nodes for their consensus addresses and automatically restarting the Tenderming service (if necessary).

looking at the tendermint code, this would require restarting the tedermint service. That together with the fact that validators don't technically need to specify sentries as persistent peers probably makes implementing this not really worth considering the effort vs benefits.

> Instead of manually disabling Tendermint's Peer exchange reactor when using sentry nodes, do that automatically (if sentry nodes are configured).

Since `disable_pex` flag is useful by itself (e.g. someone might want to connect to known trusted nodes via persistent peers and disable pex) i think having to manually disable pex reactor is fine.


However i did try to address some other "simplifications" in #2560

**Comment by kostko** [comment]
> Since disable_pex flag is useful by itself (e.g. someone might want to connect to known trusted nodes via persistent peers and disable pex) i think having to manually disable pex reactor is fine.

Yeah having an option to disable PEX manually seems reasonable, but is there ever a need for having PEX enabled on the upstream node when using sentry nodes? If not, you can do both -- keep the manual "disable PEX" option and also automatically disable PEX on the upstream node when using sentry nodes.
