### ISSUE TITLE
Registry gas costs

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2378]
Some of the registry operations (e.g., entity registration/deregistration, unfreezing a node) should probably be changed to cost gas.

**Comment by Yawning** [comment]
Should the gas cost for an entity (re-)registration scale based on how many nodes the entity claims to own?  Alternatively, should the initial node registration (not re-registrations) cost gas (might be hard to do if we want to allow people to update without it costing anything, since the node descriptor goes away)?

**Comment by kostko** [comment]
> Should the gas cost for an entity (re-)registration scale based on how many nodes the entity claims to own?

Yeah that's a good idea. But then there needs to be separate charges for entity-signed node registrations.

> Should the node registrations cost gas?
> Maybe just the initial node registration?

That would enable the node key to drain the entity's account?

> Maybe a combination of "entity registrations cost more gas if it includes more nodes", and "self-signed (vs entity signed) node registrations are gas-less"?

Yeah this makes the most sense -- so entity registrations cost more gas based on the length of the `nodes` field and entity-signed nodes must pay for gas.
