### ISSUE TITLE
oasis-node freezes when address is not valid

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2438]
If you mistype the `-a` address when running `oasis-node`, for example
```
$ oasis-node stake list -a unix:/internl.socket
```

It just freezes. This was introduced in 36020d3acae8e833c374427d84137e2609d15f16

Before, it correctly responded
```
$ go/oasis-node/oasis-node stake list  -a unix:/internl.socket
ts=2019-11-27T14:29:41.942784116Z level=warn module=cmd/stake caller=stake.go:70 msg="failed to query accounts" err="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial unix internl.socket: connect: no such file or directory\"" attempt=1
```

The same happens, if you forget `unix:` before the filename and it tries to connect to a tcp socket.

**Comment by kostko** [comment]
The reason for "freezing" is that we added the `WaitReady` gRPC option which waits for the socket/host to appear. This is useful if you want to start the client before the node is fully initialized, but it does result in an apparent freeze if you mistype the path/host.

We could make the tools emit a message saying something like "waiting for host/socket to appear".

**Comment by samohyes** [comment]
I got the same problem here. I am using non-SGX mode. After I start the node with 
`./go/oasis-net-runner/oasis-net-runner   --net.node.binary go/oasis-node/oasis-node   --net.runtime.binary target/debug/simple-keyvalue   --net.runtime.loader target/debug/oasis-core-runtime-loader   --net.keymanager.binary target/debug/oasis-core-keymanager-runtime`

It outputs 

`level=info module=oasis/net-runner caller=oasis.go:499 ts=2020-01-19T02:17:18.98411985Z msg="network started"
level=info module=net-runner caller=root.go:146 ts=2020-01-19T02:17:18.984188437Z msg="client node socket available" path=/tmp/oasis-net-runner510208045/net-runner/network/client-0/internal.sock
`

So In another terminal 
`./go/oasis-node/oasis-node stake list -a /tmp/oasis-net-runner510208045/net-runner/network/client-0/internal.sock
`

However,  it just freezes here. I don't know why.

**Comment by kostko** [comment]
@samohyes if that is the exact command that you use then the address is incorrect as it is missing the `unix:` prefix (e.g., the address should be `unix:/tmp/oasis-net-runner...` and not just `/tmp/oasis-net-runner...`).

**Comment by samohyes** [comment]
@kostko Thanks for the reply. I didn't make it clear. I tried both with the unix prefix or not. For example I tried
`./oasis-node stake list -a unix:/tmp/oasis-net-runner484498171/net-runner/network/client-0/internal.sock` just now.

But it also failed and freeze here. Is it because I am using non-SGX mode?

**Comment by matevz** [comment]
@samohyes Are you sure the socket file exists and has correct permissions?

I just tried this on a fresh Ubuntu 18.04 without SGX and it seems to work fine.
```bash
matevz@matevz-testing:~/oasis-core$ go/oasis-node/oasis-node stake list -a unix:/tmp/oasis-net-runner074765384/net-runner/network/client-0/internal.sock
0c4e9d41f014dc42685d2081fde623c6ef802e6d83318282358b4fc8c4479f83
4ea5328f943ef6f66daaed74cb0e99c3b1c45f76307b425003dbc7cb3638ed35
matevz@matevz-testing:~/oasis-core$ ls -la /tmp/oasis-net-runner074765384/net-runner/network/client-0/internal.sock
srwx------ 1 matevz matevz 0 Jan 21 11:56 /tmp/oasis-net-runner074765384/net-runner/network/client-0/internal.sock
```

**Comment by samohyes** [comment]
Thanks for the reply, I am using the ubuntu 16.04 and the whole process that I did is 

starting the ndoe

`./go/oasis-net-runner/oasis-net-runner --net.node.binary go/oasis-node/oasis-node --net.runtime.binary target/debug/simple-keyvalue --net.runtime.loader target/debug/oasis-core-runtime-loader --net.keymanager.binary target/debug/oasis-core-keymanager-runtime`

get the output

`level=info module=oasis/net-runner caller=oasis.go:499 ts=2020-01-22T02:01:01.903153067Z msg="network started"
level=info module=net-runner caller=root.go:146 ts=2020-01-22T02:01:01.903207032Z msg="client node socket available" path=/tmp/oasis-net-runner762650779/net-runner/network/client-0/internal.sock`

check the premission
`ls -la oasis-net-runner762650779/net-runner/network/client-0/internal.sock 
srwx------ 1 qiushui qiushui 0 Jan 21 18:01 oasis-net-runner762650779/net-runner/network/client-0/internal.sock
`

And in another terminal(I don't know whether I should set some env parameters  here)

`./go/oasis-node/oasis-node stake list -a unix:/tmp/oasis-net-runner762650779/net-runner/network/client-0/internal.sock`

Then it freezes.

Maybe it's because I am using ubuntu 16.04?

**Comment by samohyes** [comment]
emm, I tried with ubuntu18.04 and failed agian. This time the output is 

> ./go/oasis-node/oasis-node stake list -a unix:/tmp/oasis-net-runner052769875/net-runner/network/client-0/internal.sock
ts=2020-01-22T10:13:35.295321724Z level=warn module=oasis-node caller=common.go:212 msg="the node user has a very low RLIMIT_NOFILE, consider increasing" cur=1024 max=1048576

It freezes here.

**Comment by matevz** [comment]
The freeze was fixed by removing `WaitForReady` gRPC option by default. Also, if user just forgot to prepend `unix:` before the socket filename, it's prepended autmoatically.
