### ISSUE TITLE
CLI - support base64 encoded address parameters

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2588]
## Summary
Currently, RuntimeID, EntityID, NodeID and maybe some other parameters need to be passed as hex-encoded values when calling `oasis-node` from CLI. On the other hand, listing the entities, runtimes etc. using CLI prints JSON which has base64 encoded address. Instead of simply copy&pasting them, you need to convert it to hex value using some external tool. [Documentation also mentions this](https://docs.oasis.dev/operators/joining-the-testnet.html#staking-and-registering).

## Expected behavior
To ease copy&pasting CLI parameter values should support (at least) the formats to which they are marshalled when printing them. Right now, this is base64, so implement that beside the hex format.

**Comment by Yawning** [comment]
Like I said, as long as this doesn't change the encoding required for serialized data, I don't care.

**Comment by pro-wh** [comment]
- some strings can be valid in both encodings. decoding would have to be more complex. possibly by decoding with knowledge of what length to expect. not sure if all tooling is ready for t this kind of thing
- we should not let this make standardizing on one less appealing. let's still make output and a preferred input encoding consistent
- we should warn when accepting whichever one is less preferred

**Comment by tjanez** [comment]
As @pro-wh pointed out, supporting both encodings would be complex and we should decide on a preference anyway.

Also, at this stage, we can still make such breaking changes to the CLI, so we can sort this out more cleanly.

Since JSON serialization will always use base64 encoding and all the Pem files containing public keys already use base64 encoding, it is perhaps most convenient to always use base64 encoding when something is either outputted by a CLI command or given as an input to a CLI command.
