### ISSUE TITLE
oasis-node crash during Ethereum runtime's genesis-playback

### ISSUE THREAD

**Issue by matevz** [oasislabs/oasis-core#2611]
Steps to reproduce:
1. From oasis-core run `oasis-net-runner` as stated in the README,
2. Wait a few moments so the nodes get synced,
3. In another terminal from oasis-runtime run `genesis-playback state-2999999.json runtimestates.json --commit-every 10000 -a $ADDR --runtime-id 8000000000000000000000000000000000000000000000000000000000000000` where `$ADDR` is the path to you storage socket.
4. Wait until around transaction 110k, oasis-node crashes.

Attached [storage-0/console.log](https://github.com/oasislabs/oasis-core/files/4127704/console.log) from oasis-core a48cd81fb8a2be3eba53404b1417282e91b589c7.

It's 499032-th call to CompactMarshalBinary() that crashes, `n.Value` is not accessible.

Note: genesis-playback works, if `--commit-every 1000` is passed.

**Comment by kostko** [comment]
This is very likely due to a bug in the leaf node unmarshaller:
https://github.com/oasislabs/oasis-core/blob/master/go/storage/mkvs/urkel/node/node.go#L625

Currently it just references a slice of the data which is being unmarshaller. Since this is used when retrieving nodes from a memory mapped database (e.g., Badger), the slice may become invalid or be overwritten with other data.

Can you check if just fixing it to copy the value helps?

**Comment by matevz** [comment]
Works, thanks.

**Comment by matevz** [comment]
fixed
