### ISSUE TITLE
Bump fxamacker/cbor to 2.x

### ISSUE THREAD

**Issue by kostko** [oasislabs/oasis-core#2635]
The recently made some minor API changes which should be easy to integrate. [The release](https://github.com/fxamacker/cbor/releases) also brings performance and memory use improvements.

Next release (v2.1) will also add support for CBOR tags which may be useful.

**Comment by fxamacker** [comment]
Hi @kostko!  I [released v2.2](https://github.com/fxamacker/cbor/releases) with a bugfix and additional security-related settings:  `MaxNestedLevels`, `MaxArrayElements`, `MaxKeyPairs`, `IndefLength` (allow/forbid), and `TagsMd` (allow/forbid).  

v2.2 also added CBOR byte string <--> Go byte array was added (slice was already supported.)

v2.2 is slightly faster than v2.1, but biggest gains came from v2.1 -- struct using `keyasint` tag (like COSE and CWT) is about __24-28% faster__ and __53-61% fewer allocs__ compared to v1.x and 2.0.

v2.1 added CBOR tags and option to detect duplicate map keys.

Please let me know if I can help!

**Comment by kostko** [comment]
Cool, we'll bump to v2 soon. I just filed https://github.com/fxamacker/cbor/issues/178, @fxamacker what do you think about adding an option for stricter decoding?

**Comment by fxamacker** [comment]
Option(s) for stricter decoding is coming but I need to be cautious because "strict mode" and even the word "strict" is gone in the draft 7049bis.

I want to provide preset options for deterministic encoding/decoding that round trips without violating RFC 7049 and newer 7049bis.  This would require stricter decoding.

BTW, 7049bis is moving away from using the word "canonical".  It prefers bytewise-lexicographic sort instead of length-first sort (RFC 7049 canonical).  I heard 7049bis might get approved "later this year".

https://tools.ietf.org/id/draft-ietf-cbor-7049bis-12.html
